// Danh sách các trường đại học ở Việt Nam
export const UNIVERSITIES = [
    // Đại học quốc gia
    'Đại học Quốc gia Hà Nội',
    'Đại học Quốc gia Thành phố Hồ Chí Minh',
    'Đại học Quốc gia Đà Nẵng',
    
    // Các trường đại học lớn
    'Đại học Bách Khoa Hà Nội',
    'Đại học Bách Khoa Thành phố Hồ Chí Minh',
    'Đại học Kinh tế Quốc dân',
    'Đại học Kinh tế Thành phố Hồ Chí Minh',
    'Đại học Ngoại ngữ - Đại học Quốc gia Hà Nội',
    'Đại học Ngoại ngữ Thành phố Hồ Chí Minh',
    'Đại học Sư phạm Hà Nội',
    'Đại học Sư phạm Thành phố Hồ Chí Minh',
    'Đại học Y Hà Nội',
    'Đại học Y Thành phố Hồ Chí Minh',
    'Đại học Công nghiệp Hà Nội',
    'Đại học Công nghiệp Thành phố Hồ Chí Minh',
    'Đại học Thương mại',
    'Đại học Nông nghiệp Hà Nội',
    'Đại học Nông nghiệp Thành phố Hồ Chí Minh',
    'Đại học Xây dựng',
    'Đại học Giao thông Vận tải Thành phố Hồ Chí Minh',
    'Đại học Giao thông Vận tải Hà Nội',
    'Đại học Lâm nghiệp',
    'Đại học Lương Thế Vinh',
    'Đại học Mở Thành phố Hồ Chí Minh',
    'Đại học Công nghiệp Hà Nội',
    'Đại học Kinh tế - Kỹ thuật Công nghiệp',
    'Đại học Văn Hiến',
    'Đại học Tây Đô',
    'Đại học An Giang',
    'Đại học Cần Thơ',
    'Đại học Huế',
    'Đại học Thái Nguyên',
    'Đại học Quảng Bình',
    'Đại học Hải Phòng',
    'Đại học Hạ Long',
    'Đại học Đà Nẵng',
    'Đại học Nha Trang',
    'Đại học Quy Nhơn',
    'Đại học Tây Nguyên',
    'Đại học Sài Gòn',
    'Đại học Cần Thơ',
    'Đại học Tôn Đức Thắng',
    'Đại học Ngoại thương',
    'Đại học Công nghệ Sài Gòn',
    'Đại học FPT',
    'Đại học Aptech',
    'Đại học Greenwich Việt Nam',
    'Đại học RMIT',
    'Đại học Huflit',
    'Đại học Văn Lang',
    'Đại học Quốc phòng',
    'Học viện Quân sự',
    'Học viện Cảnh sát Nhân dân',
     // TP.HCM
    'Đại học Công nghệ Thông tin - ĐHQG TP.HCM',
    'Đại học Khoa học Tự nhiên - ĐHQG TP.HCM',
    'Đại học Khoa học Xã hội và Nhân văn - ĐHQG TP.HCM',
    'Đại học Quốc tế - ĐHQG TP.HCM',
    'Đại học Công nghệ TP.HCM',
    'Đại học Nông Lâm TP.HCM',
    'Đại học Hoa Sen',
    'Đại học Nguyễn Tất Thành',
    'Đại học Gia Định',
    'Đại học Hồng Bàng',
    'Đại học Tài chính - Marketing',
    'Đại học Ngân hàng TP.HCM',
    'Đại học Luật TP.HCM',
    'Đại học Kiến trúc TP.HCM',
    'Đại học Mỹ thuật TP.HCM',
    'Đại học Sư phạm Kỹ thuật TP.HCM',
    'Đại học Quốc tế Hồng Bàng',
    'Đại học Công nghệ Sài Gòn',
    'Đại học Văn hóa TP.HCM',

    // Đồng Nai - Bình Dương
    'Đại học Thủ Dầu Một',
    'Đại học Bình Dương',
    'Đại học Quốc tế Miền Đông',
    'Đại học Đồng Nai',
    'Đại học Lạc Hồng',
    'Đại học Công nghệ Đồng Nai',

    // Cần Thơ - miền Tây
    'Đại học Nam Cần Thơ',
    'Đại học Kỹ thuật - Công nghệ Cần Thơ',
    'Đại học Trà Vinh',
    'Đại học Đồng Tháp',
    'Đại học Tiền Giang',
    'Đại học Bạc Liêu',
    'Đại học Kiên Giang',
    'Đại học Cửu Long',
    'Đại học Võ Trường Toản',

    // Đông Nam Bộ
    'Đại học Bà Rịa - Vũng Tàu',
    'Đại học Dầu khí Việt Nam',

    // Tây Nam Bộ
    'Đại học Y Dược Cần Thơ',
];

export const getUniversitiesList = () => UNIVERSITIES.sort();
